'use strict';
import * as colors from './colors';
export {default as shades} from './shades';
import * as typo from './typo';
import * as contrast from './contrast';
export {default as elevation} from './elevation';
export {default as withMaterialTheme} from './withMaterialTheme';
export {default as withMaterialStyles} from './withMaterialStyles';
export {default as MaterialTheme, getMaterialTheme} from './MaterialTheme';
export {default as ThemeProvider} from './ThemeProvider';
export {colors, typo, contrast};
